### PR TITLE
add users for group profile within admin ui

### PR DESCRIPTION
**Pull request by melissapalmer**

### CODE REVIEW

**Comment by menski** [comment]
Hi Melissa,

thanks for your pull request. I created a jira ticket for review [1].

Cheers,
Sebastian

[1] https://app.camunda.com/jira/browse/CAM-3469

**Comment by SebastianStamm** [comment]
Hi Melissa,

I have merged your pull request. I changed the code so it respects our contribution guidelines [1].

Cheers,
Sebastian

**Comment by melissapalmer** [comment]
Hi Sebastian, 

Great thanks for that... I will try to make sure about the contribution guidelines next time. 

Thanks 
Melissa

**Comment by melissapalmer** [comment]
Hi Sebastian, 

Great thanks for that... I will try to make sure about the contribution guidelines next time. 

Thanks 
Melissa

**Pull request closed without merging**
